### ISSUE TITLE
Add a household GPS tracking functionality to the system to enable the following;

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#1116]
- [ ] Mandatory recording of GPS data for each service or referral, irrespective of the type of service provided.

- [ ] Mandatory recording of GPS data during quarterly visitations. The form should not allow saving unless the user is near the household being visited.

- [ ] Date exports which should include information on the distance of each service from the home.

- [ ]  During each visitation recorded on tablets, the system shall display the distance between where the service was provided and the beneficiary's household.

- [ ] Any change in the home GPS coordinates must require approval from a higher-ranking officer. The system should provide a secure mechanism for obtaining and verifying such approvals.
