### ISSUE TITLE
ECAP - List of pending workers received from meetings PCZ and Internal testing. -09/06/2022

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#888]
**NOTE: This issue comprises of issues that are currently still open on the project board and some new issues of what we have that is still being worked on
**

- [ ] Finish working on the DELETE feature, to allow caseworkers delete only what they have added on the platform.
- [ ] If a child is 6 weeks old and above and the user clicks on 10 weeks, 14 weeks, 9 months or 18 months on the question “Has the child received the following vaccinations ?” This should not be possible.
- [ ] Include a feature for tracking DBS (HIV Test for HEI) and viral load due dates, Issue  #842 
- [ ] Create a new register name  “WE group referrals” to track the “WE monthly loans”.  issue #868  )
- [ ] Finish working on the graduation assessment form 
- [ ] Finish working on the referral form completely. 
- [ ] The caseworker’s profile to show the total number of VCAs and Households that he or she has enrolled.
- [ ] Creating the new feature “Child development plan”. #665 
- [ ] The field services to be referred on the case plan should show the services that appear on the referral form. It should be a checklist. - New Issue - Client feedback
- [ ] Working on the Dashboards.

**Comment by gladysyabs** [comment]
@chobela  we need to to prioritize the graduation assessment, because caseworkers are now being told to graduate the VCAs
